### ISSUE TITLE
Websocket (WS to WSS) reverse proxy (and/or Docker support?)

### ISSUE THREAD

**Issue by peanutlasko** [Marekkon5/onetagger#111]
Hi @Marekkon5 , I know we've chatted once before about some Onetagger questions. First off let me state that I know you guys are a small 2-man team, and expecting extensive fixes/testing/troubleshooting for **FREE** software is not something that's feasible. 

Before I dig into my issue, let me explain what I'm trying to accomplish. Right now I have a homelab/server in which I have several docker containers that run, including one that hosts my reverse proxy. All these services provide lots of different things, but one of them is for all of my audio/DJ management. 

**OneTagger is a godsend to my DJ workflow.** Right now I use it locally on my Mac Pro (server) to tag all my music, and then sync it with my Macbook Pro, which in turn I import into Rekordbox/Traktor.

Ideally, what I am trying to accomplish is the need to not be physically sitting at my Home Server. I'd like to be able to log into OneTagger via the web using the --expose --server and tag all my tracks on any PC, Anywhere. My Home server already has an automated way to use Spotify, download tracks, sort them into folders, etc. So the final piece of my puzzle is getting Onetagger to work via the web. I can do this from any computer with a web browser, securely. 

With all that out of the way, let me get a little deeper. I have a reverse proxy as I mentioned that exposes all my services. It redirects all HTTP traffic to HTTPS. I've got about 20ish applications running that work perfectly fine with this. However, with Onetagger an issue arises because of the insecure WS socket connection. I've dug into this and found several ways to mitigate the issue ([here](https://community.traefik.io/t/websocket-does-not-upgrade-ws-to-wss/12017))

The UI loads, but after a moment I'm getting a websocket connection ([screenshot here](https://imgur.com/NSMgVwc))

Now, let me be the first to say - i understand this is a pretty fringe use-case. My other alternative I've tried was to create a docker container (which I was about 90% successful), however I ran into a problem when clicking the "Browse" buttons because I guess building it from source there's no way to display via the web a dialogue box? The error I got on the docker container was:

```
missing software! (we will try basic console input)


 ___________

/           \ 

| tiny file |

|  dialogs  |

\_____  ____/

      \|

tiny file dialogs on UNIX needs:

   applescript or kdialog or yad or Xdialog

or zenity (or matedialog or shellementary or qarma)

or python (2 or 3) + tkinter + python-dbus (optional)

or dialog (opens console if needed) ** Disabled by default **/

or xterm + bash (opens console for basic input)

or existing console for basic input
```

I tried installing python3 and tkinter and python-dbus, with no such luck.

In any case, I'm hoping to either A) get a HTTPS/WSS socket that works which I can use for my reverse proxy, or B) some effort into the Docker container (which I have some experience with and would be happy to perform testing and updates).

Now all that being said, what I'm asking for is a lot. I don't expect ANY of this for free as a matter of fact. I'm going to submit a donation now, and additionally if you guys decide to tackle this I'm happy to continue to compensate you for your efforts.

**Comment by Marekkon5** [comment]
Hello, thanks for trying to use this project in such a way, however there are some issues:

1. The socket not connecting error - I will have to probably try to recreate your setup and try it myself. I am pretty certain the issue is somewhere with the socket not being properly forwarded / decrypted to HTTP.
2.  As for the docker - well I recommend just using some latest Ubuntu base image and downloading the binary (and dependencies). I don't think there needs to be any advanced/complicated setup for this.
3. As for the browse button - 1T was designed to be used on desktop, so the `tinyfiledialogs` library opens the native file browser (which on server isn't available, so it shows you that long error). This requires me to make my own file browser within 1T, which will take me some time and effort.
4. Player in QT won't work for you at all - it is server side, the music would play from the server, not the browser, and there isn't much I can do, because of the codecs support.

**Comment by peanutlasko** [comment]
Thanks for the feedback. One other log I forgot to attach was the console output from OneTagger when attempting to hit the page:

```
2022-05-06 15:20:16 [ERROR] onetagger_shared: PANIC: panicked at 'called `Result::unwrap()` on an `Err` value: HandshakeError::Failure(Protocol(HttparseError(Token)))', crates/onetagger/src/socket.rs:151:57
2022-05-06 15:20:16 [ERROR] onetagger_shared: LOCATION: File: crates/onetagger/src/socket.rs, Line: 151
```

My docker container works perfectly, its just the file browser issue that's the problem (and the websocket).

I see what your saying now though - when I access via web on my macbook (not running 1T) and hit the play button, the audio comes out of my Mac Pro (server running 1T). That's too bad. 

So even if the socket connection were fixed, and/or a docker container, I still couldn't listen to my tracks remotely and tag them. Oh well, maybe someday for a v2.0 release or something. I'll just have to live :)

**Comment by Marekkon5** [comment]
Hello, in the latest commit I've added: 
1. Client side file browser - it's been planned for some time, so I just added it.
2. Client side music player. However because the browser doesn't support all the codecs 1T does, 1T internally converts the audio file into WAV, so the browser can stream it. This causes some small delays when playing and seeking, however it enables you to play all the audio files remotely.

As for the secure sockets - I think issue is on your end with your reverse proxy setup. Do you mind sharing what programs/configs do you use?

Also to test the changes you can get the binary from the Actions tab. Let me know if it works for you. Thanks

**Comment by peanutlasko** [comment]
Hey thanks for this update!

I'm using Traefik as my reverse proxy. I can share some of my configuration with you, hopefully it makes sense. 

First I defined my entry point in Traefik.yml

```
entrypoints:
  http:
    address: ":80"
  https:
    address: ":443"
  ws:
    address: ":36912"
```

Next, I have my middlewares configured for all my services which controls headers:

```
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
          - "X-Forwarded-Proto"
          #- "X-Forwarded-For"
        stsSeconds: 63072000
        #sslProxyHeaders:
          #X-Forwarded-Proto: "https"
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        # frameDeny: true #overwritten by customFrameOptionsValue
        #customFrameOptionsValue: "allow-from https:example.com" #CSP takes care of this but may be needed for organizr.
        contentTypeNosniff: true
        browserXssFilter: true
        # sslForceHost: true # add sslHost to all of the services
        # sslHost: "example.com"
        referrerPolicy: "same-origin"
        # Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
        # the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
        # contentSecurityPolicy: "frame-ancestors '*.example.com:*';object-src 'none';script-src 'none';"
        #permissionsPolicy: "camera=()" #"; geolocation=(); microphone=(); payment=(); usb=(); vr=()"
        FeaturePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
        customResponseHeaders:
          Content-Security-Policy: "upgrade-insecure-requests"
          #Content-Security-Policy-Report-Only: "upgrade-insecure-requests"
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
        customRequestHeaders:
          X-Forwarded-Proto: "https,wss,ws"
```

To note, I had to add the "wss,ws" for the CustomRequestHeaders to get the GUI to load. 

Last, I have a custom rule for Onetagger (right now I'm not using a docker container, I'm just testing running it locally on my Mac)

```
http:
  routers:
    onetagger-rtr:
      rule: "Host(`onetagger.xxxxxx.net`)" 
      entryPoints:
        - https
      middlewares:
        - chain-no-auth
      service: onetagger-svc
      tls:
        certResolver: dns-cloudflare

    onetagger-rtr-ws:
      rule: "Host(`onetagger.xxxxxxx.net`)"
      entryPoints:
        - ws
      middlewares:
        - chain-no-auth
      service: onetagger-svc-ws
      tls:
        certResolver: dns-cloudflare


  services:
    onetagger-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.1.101:36913"  # or whatever your external host's IP:port is 
    onetagger-svc-ws:
      loadBalancer:
        sticky:
          cookie: {}
        servers:
          - url: "wss://192.168.1.101:36912"
```

In my testing, I've tried several different things. Sticky cookies, changing the URL from "wss" to "ws", or "http"/"https". Still cannot get it to connect for some reason. One reference I found on the web links to [here](https://community.traefik.io/t/websocker-to-different-port/10952/5), which I followed with no luck. 

I will test your latest changes and let you know.
